### ISSUE TITLE
jbig2, wildcard does not work in Windows.

### ISSUE THREAD

**Issue by zvezdochiot** [agl/jbig2enc#108]
Hi all.

OS: Windows
Release: 0.30

@U235  [say](http://forum.ru-board.com/topic.cgi?forum=5&topic=17599&start=3860#6):
>it works on the example file from the doc, it creates a multi-page pdf with a common dictionary. 
>`jbig2 -s -a -p -v feyn.tif feyn2.tif feyn3.tif && python jbig2topdf.py output > feyn.pdf`
>The inconvenient thing is that file names need to be listed, wildcard characters do not work.. 
>Well, instead of python3, I just need to call python.
>I used the binary from the release. 
>Python 3.12.3

**Comment by zdenop** [comment]
This windows (cmd?) problem.
https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths
There is the solution from [MS](https://learn.microsoft.com/en-us/cpp/c-language/expanding-wildcard-arguments
) for Visual Studio (I will commit it later) but I am not sure about msys build or cross compiling.
IMO we should focus on setting up GithubAction so we can test multiple build system.
