### ISSUE TITLE
Endianness problem with jbig2

### ISSUE THREAD

**Issue by khukhu** [agl/jbig2enc#22]
Hi all,

I have successfully built Leptonica library in Ubuntu10.04. Then I have compiled jbig2  also and used it for compressing many .bmp images in Ubuntu 10.04.

Now I have cross compiled leptonica and jbig2 for avr32 NGW100 micro controller. But when I am executing the jbig2.elf on the avr32 NGW100, I am getting the following error

Error in pixReadStream: Unknown format: no pix returned
Error in pixRead: pix not read

Is this error related to the endianness problem of bmp images.

**Comment by zdenop** [comment]
Duplicate to #23
