### ISSUE TITLE
Changing endianness of Leptonica Library

### ISSUE THREAD

**Issue by khukhu** [agl/jbig2enc#23]
Hi,
Can I change the endianness of Leptonica Library in some way. 
I hace crossed compiles Leptonica library and jbig2 encoder for AVR32 microcontroller (Linux based and it is big endian). 

How can change the endianness of Leptonica Library, so that jbig2 encoder can be used on my target architecture.
I found a file name endianness.h in the src directory of Leptonica Library.

Please give me any clue or suggestion. Any help will be highly appreciated. Thank you in advance.

**Comment by zdenop** [comment]
@DanBloomberg : Can you have a look at this?
