### ISSUE TITLE
Lossless ?

### ISSUE THREAD

**Issue by dbuenzli** [agl/jbig2enc#24]
Hello, 

I tried jbig2enc on some files but the result ends with unwanted letter swaps (n/u, b/h, I can provide a test file if needed). 

Is it possible to get lossless compression with jbig2enc ? Tried with -r but it tells me to bug agl. 

Thanks,

Daniel

**Comment by annulen** [comment]
Is it possible to generate PDF with lossless compression? pdf.py doesn't seem to work without symbols file

**Comment by agl** [comment]
@annulen Using generic region coding is lossless.

pdf.py is an example of the more complex PDF integration. Generic region coding is just like any other image file, however, and should be simple enough to embed in a PDF.

**Comment by annulen** [comment]
Sorry for possibly off-topic question, but what open source tools should I use to bundle PDF from these generic coded JBIG2 files? Google search gives me only jbig2 -s + pdf.py option

**Comment by rhatlapa** [comment]
Quite long time ago I've created project using IText and PDFBox libraries to replace images in PDF with their recompressed versions using JBIG2 [1]. Maybe it could be useful for your usecase or you could get some inspiration how to use those libraries and write some simple PDF generator.

[1] https://code.google.com/p/pdfrecompressor/

**Comment by annulen** [comment]
@rhatlapa, thanks for trying to help but it seems like pdfrecompressor uses the same dictionary coding (-s) as pdf.py, and I don't see any way to disable it to use lossless encoding.

@agl: from what you've written it seems that bundling generic coded JBIG2 files into one PDF is simpler task than what pdf.py does. What tool are you using for this task?

**Comment by agl** [comment]
I think that `pdf.py` can reasonably easily be tweaked to bundle standalong JBIG2 images into a PDF but I don't have anything lying around.

**Comment by kmlyvens** [comment]
Indeed, here is a very quick version of the pdf.py script that takes a list of jbig2 files as arguments and produces a pdf to stdout – I only had to remove DecodeParms reference to the symbols file:
https://gist.github.com/kmlyvens/b532c7aec2fe2bd8214ae2b3faf8f741

Now I am able to produce a pdf by these commands:

for f in *.pbm; do jbig2 -p -v "$f" > "${f%.pbm}.jb2"; done
~/pkg/jbig2enc/pdfsimp.py *.jb2 > foo.pdf
