### ISSUE TITLE
Character substitution in cyrillic texts witih Serif fonts?!

### ISSUE THREAD

**Issue by egalion** [agl/jbig2enc#26]
Hello, I find this bug very strange. I thought that the program treated the files as images and does not operate on characters. But it does. I use Ubuntu 11.04, jbig2enc was complied from source downloaded in the autumn of 2011. I use the following command for conversion:

jbig2 -b J -d -p -s *.jpg; pdf.py J > JBIG2.pdf

I haven't noticed any problems with texts in English, but when I do conversion of images, containing texts in cyrillic, it gives problems with Serif fonts, especially with Times New Roman. A picture is worth a thousand words, that is why I provide a link to a file containing 1) the original pdf file 2) the jpg file used as a source 3) the final pdf file, produced with jbig2enc. I include three such sets - for documents with Times New Roman, Liberation Serif, and Arial.

There are no problems for documents with Arial fonts. Liberation Serif leads to some character substitutions (see and compare word 1 on row 6 in the original and jbig2 encoded file). With Times New Roman character substitution is almost on every row (for an example see word 3 on row 1).

The files are here:
http://www.2shared.com/file/F-iXXDdC/jbig_files.html

**Comment by zdenop** [comment]
Should be fixed with  https://github.com/agl/jbig2enc/pull/103/
