### ISSUE TITLE
fatal error LNK1104 for 'zlib125-static-mtdll-debug.lib'

### ISSUE THREAD

**Issue by Fendayen** [agl/jbig2enc#38]
I am receiving the following fatal error link when attempting to build the solution in VC++ 2008:

LINK : fatal error LNK1104: cannot open file 'zlib125-static-mtdll-debug.lib'

As a note, changing the runtime library to other versions had no impact on the error.

**Comment by nmdwolf** [comment]
I tried to compile everything yesterday but ran into this same issue. However, the link at https://github.com/agl/jbig2enc/blob/master/INSTALL was for vs2008 and is officially dead. What is the current way out of this situation?
