### ISSUE TITLE
Wrong Output Jbig2 image

### ISSUE THREAD

**Issue by ramisahoori** [agl/jbig2enc#49]
Hi,

I have built leptonica successfully, and use it to encode a Pbm file and save it as jbig2 file format.
this worked with me successfully with a lot of files, but with this pbm
https://onedrive.live.com/redir?resid=BF8D672F16E7537C!54872&authkey=!AGOomuu4Y2rH_Ik&ithint=file%2cpbm
the result is wrong, there are errors in the text, here is the resulting jb2 image.
https://onedrive.live.com/redir?resid=BF8D672F16E7537C!54871&authkey=!ABN7KWMhSOgSM9U&ithint=file%2cjb2
I encoded with -s -v commands. any help here will be appreciated.
Thanks all.

**Comment by agl** [comment]
Using symbol mode does run the risk of contoots. See the [original paper](http://www.leptonica.com/papers/google-jbig2.pdf) or just use generic-region coding.
