### ISSUE TITLE
Improve lossy compression ratio by implementing Kruskal’s algorithm for minimum spanning tree

### ISSUE THREAD

**Issue by dwightkelly** [agl/jbig2enc#5]
Y. Ye and P. Cosman developed a method for improving lossy compression ratios using Kruskal’s algorithm for minimum spanning trees to reduce the size of the symbol dictionary.

"JBIG2 symbol dictionary design based on minimum spanning trees" 
Proceedings of the First International Conference on Image and Graphics (ICIG), pp. 54-57, Tianjin, China, August 2000

**Comment by zdenop** [comment]
@DanBloomberg : Any idea about this?

**Comment by DanBloomberg** [comment]
It's an interesting idea, but not on the list of things to do.
I just found out that djvu compression of 1 bpp images makes a very good symbol directory, but I don't have any details.

BTW, Kruskal's niece Karen is a very good harpsichord player!
