### ISSUE TITLE
Update on patent situation

### ISSUE THREAD

**Issue by mia-0** [agl/jbig2enc#58]
Looks like all the relevant patents have expired:

Japanese Patent 2128110, Jan. 1989 (expired)
     Mitsubishi Electric Corp., Ono (F.) et al.: CODING METHOD OF IMAGE INFORMATION

Japanese Patent 2128115, Feb. 1990 (expired)
     Mitsubishi Electric Corp., Ono (F.) et al.: CODING SYSTEM

US Patent 4286256, filed November 28, 1979 (expired)
     IBM, Method and means for arithmetic coding using a reduced number of operations

US Patent 4295125, filed April 28, 1980 (expired)
     IBM, A method and means for pipeline decoding of the high to low order pairwise combined digits of a decodable set of relatively shifted finite number of strings

US Patent 4410916, filed July 9, 1981 (expired)
     Compression Labs Inc, Dual mode facsimile coding system and method

US Patent 4463342, filed June 14, 1979 (expired)
     IBM, A method and means for carry-over control in a high order to low order combining of digits of a decodable set of relatively shifted finite number strings

US Patent 4463386, filed May 3, 1982 (expired)
     IBM, Facsimile data reduction

US Patent 4467317, filed March 30, 1981 (expired)
     IBM, High-speed arithmetic compression using concurrent value updating

US Patent 4633490, filed March 15, 1984 (expired)
     IBM, Symmetrical adaptive data compression/decompression system

US Patent 4652856, filed February 4, 1986 (expired)
     IBM, A multiplication-free multi-alphabet arithmetic code

US Patent 4749983, filed April 29, 1986 (expired)
     IBM, Compression of multilevel signals

US Patent 4891643, filed September 15, 1986 (expired)
     IBM, Arithmetic coding data compression/de compression by selectively employed, diverse arithmetic encoders and decoders

US Patent 4901363, filed September 28, 1988 (expired)
     IBM, System for compressing bi-level data

US Patent 4905297, filed November 18, 1988 (expired)
     IBM, Arithmetic coding encoder and decoder system

US Patent 4922545, filed February 10, 1989 (expired)
     KDD, Facsimile image encoding method

US Patent 4935882, filed July 20, 1988 (expired)
     IBM, Probability adaptation for arithmetic coders

US Patent 5099440, filed January 5, 1990 (expired)
     IBM, Probability adaptation for arithmetic coders

US Patent 5884014, filed May 23, 1996 (expired)
     Xerox, Fontless structured document image representations for efficient rendering

US Patent 6020972, filed November 14, 1997 (expired)
     Xerox, System for performing collective symbol-based compression of a corpus of documents

**Comment by agl** [comment]
That would be nice. However, I'm not qualified to make a judgement here and the docs deliberately take a hands-off approach to avoid the impression that any competent opinion is being presented.

It's good that many potentially applicable patents have expired but I don't think that we can say much more than we do now about this.
