### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by fxcoudert** [agl/jbig2enc#60]
It's been a long long time since the last release, and there are build issues (related to leptonica) and runtime issues (https://github.com/Homebrew/homebrew-core/issues/25714) that have been fixed since 0.28 was released.

Could you please tag a new release? This would allow us (Homebrew) to distribute this new version, without patching :)

Many thanks in advance

**Comment by agl** [comment]
https://github.com/agl/jbig2enc/releases/tag/0.29

**Comment by fxcoudert** [comment]
Thanks!
