### ISSUE TITLE
could you guys re-upload the patch please?

### ISSUE THREAD

**Issue by DingoDog** [agl/jbig2enc#70]
could you guys re-upload the patch please?

_Originally posted by @useretail in https://github.com/agl/jbig2enc/issues/10#issuecomment-808750480_

I reuploaded patch on my site:

http://dokupuppylinux.info/media/jbig2.patch.zip

**Comment by useretail** [comment]
mirror: [https://pastebin.com/raw/WT4TwUxZ](https://pastebin.com/raw/WT4TwUxZ)

**Comment by zdenop** [comment]
Duplicate to #10
