### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by IdleThought** [agl/jbig2enc#76]
Quick question about this repo, I see 25 current issues and 6 PRs open for it, but still this seems to be the go to for the jbig2 open source encoder. I was curious if this repo was maintained by anyone still? If so, is there a plan on any updates?

**Comment by ambiamber** [comment]
"To do is to be". "If it walks like a duck and it quacks like a duck...".

There is a tab on this page labeled "Insights".  On that tab there is a "Network" tab. Once you get there, you will se a chart. Swipe the chart so newer forks are visible. Click on the owner of the fork. They you can read their updates and decide if it is better than this abandoned repo.

**Comment by zdenop** [comment]
No, this repo is not dead.
